services:
  mariadb:
    image: mariadb:latest
    container_name: matsfx-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matsfx-app
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: matsfx-mariadb
    ports:
      - "${PORT}:80"
    depends_on:
      - mariadb
      - minio
    volumes:
      - .:/var/www/html
    pull_policy: build

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: matsfx-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_FORCE_SSL: "false"
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    depends_on:
      - mariadb
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: matsfx-minio
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ZyCJyO9P1De546MAdLJO3shKQ93govZTKlX3f
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_ADMIN_PORT}:9001"
    volumes:
      - minio_data:/data

volumes:
  mariadb_data:
  minio_data: